// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import DeleteEvaluatorModalController from "./delete_evaluator_modal_controller";
application.register("delete-evaluator-modal", DeleteEvaluatorModalController);

import EvaluationCriteriaController from "./evaluation_criteria_controller";
application.register("evaluation-criteria", EvaluationCriteriaController);

import EvaluationFormController from "./evaluation_form_controller";
application.register("evaluation-form", EvaluationFormController);

import HotdogController from "./hotdog_controller";
application.register("hotdog", HotdogController);

import SubmissionDetailsController from "./submission_details_controller";
application.register("submission-details", SubmissionDetailsController);

import ModalController from "./modal_controller";
application.register("modal", ModalController);

import SortFilterMenuController from "./sort_filter_menu_controller";
application.register("sort-filter-menu", SortFilterMenuController);

import UnassignEvaluatorSubmissionModalController from "./unassign_evaluator_submission_modal_controller";
application.register("unassign-evaluator-submission-modal", UnassignEvaluatorSubmissionModalController);