version: '2'
checks:
  similar-code:
    config:
      threshold: 75
plugins:
  brakeman:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-56-3
exclude_patterns:
- .nix-bundler
- config/
- db/
- vendor/
-  "**/vendor/**/*"
- app/assets/images/
- spec/**/*