default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("POOL_SIZE", 15) %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: challenge_gov_dev

test:
  <<: *default
  database: challenge_gov_test

staging:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  url: <%= ENV["DATABASE_URL"] %>