default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("POOL_SIZE", 15) %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: challenge_gov_dev

test:
  <<: *default
  database: challenge_gov_test

dev:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("POOL_SIZE", 15) %>
  url: <%= ENV["DATABASE_URL"] %>

staging:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("POOL_SIZE", 15) %>
  url: <%= ENV["DATABASE_URL"] %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("POOL_SIZE", 15) %>
  url: <%= ENV["DATABASE_URL"] %>
